### ISSUE TITLE
there is a bug when channel register after cancel a selected key

### ISSUE THREAD

**Issue by taojiaenx** [barchart/barchart-udt#80]
When you first register a channel in the selector, the nio channel will save a key(not SelectKeyUDT).Howver the cancel of the select key is overrided by the barchart,and you will never remove the key that registerd before

**Comment by taojiaenx** [comment]
java.nio.channels.CancelledKeyException
	at com.barchart.udt.nio.SelectionKeyUDT.assertValidKey(SelectionKeyUDT.java:135)
	at com.barchart.udt.nio.SelectionKeyUDT.interestOps(SelectionKeyUDT.java:359)
	at java.nio.channels.spi.AbstractSelectableChannel.register(AbstractSelectableChannel.java:201)
	at org.apache.hadoop.net.SocketIOWithTimeout$SelectorPool.select(SocketIOWithTimeout.java:349)
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:159)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:161)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:131)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:118)
	at java.io.FilterInputStream.read(FilterInputStream.java:83)
	at org.apache.hadoop.hdfs.protocolPB.PBHelper.vintPrefixed(PBHelper.java:2278)
	at org.apache.hadoop.hdfs.RemoteBlockReader2.newBlockReader(RemoteBlockReader2.java:424)
	at org.apache.hadoop.hdfs.BlockReaderFactory.getRemoteBlockReader(BlockReaderFactory.java:891)
	at org.apache.hadoop.hdfs.BlockReaderFactory.getRemoteBlockReaderFromUdt(BlockReaderFactory.java:689)
	at org.apache.hadoop.hdfs.BlockReaderFactory.build(BlockReaderFactory.java:354)
	at org.apache.hadoop.hdfs.DFSInputStream.blockSeekTo(DFSInputStream.java:635)
	at org.apache.hadoop.hdfs.DFSInputStream.readWithStrategy(DFSInputStream.java:844)
	at org.apache.hadoop.hdfs.DFSInputStream.read(DFSInputStream.java:896)
	at java.io.DataInputStream.read(DataInputStream.java:100)
	at org.apache.hadoop.io.IOUtils.copyBytes(IOUtils.java:85)
	at org.apache.hadoop.io.IOUtils.copyBytes(IOUtils.java:59)
	at org.tje.test.hdfs.TestHdfs.main(TestHdfs.java:32)
there is stacktrace
